export {default as Nav} from './nav/Nav'
export {default as Home} from './home/Home'
export {default as Order} from './order/Order'
export {default as About} from './about/About'
export {default as FAQ} from './FAQ/FAQ'
export {default as Footer} from './footer/Footer'